### ISSUE TITLE
v0.2.0 releases doesn't match the Documentation

### ISSUE THREAD

**Issue by unlinking** [niklasfjeldberg/nuxt-multi-tracker#2]
https://github.com/niklasfjeldberg/nuxt-multi-tracker/blob/fcff54fb59ce4e62ea0bcdc2252086417f86f894/src/runtime/plugins/multiAnalytics.client.ts#L6

The plugin is not updated in 0.2.0 release. 

https://github.com/niklasfjeldberg/nuxt-multi-tracker/archive/refs/tags/v0.2.0.zip

Still has the old name multiAnalytics in plugin and composables, please release a new release.

**Comment by niklasfjeldberg** [comment]
Hi @unlinking, yes that's right. I had to change the module name before release and messed up. The module is under heavy development, but I will probably release a new version today that includes a lot of updates and fixes. If you have any other requests I am happy to hear them!

If you look at the current master branch you will see it's fixed: https://github.com/niklasfjeldberg/nuxt-multi-tracker/blob/master/src/runtime/plugins/multiTracker.client.ts
